name: plantEcommerce

services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file: ./backend/config/config.env
    depends_on:
      - mongo
